const bebida = [
  //bebidas vampiros
  {
    bebida: 1,
    cliente: vampiro,
    precio: 10,
    nombre: "Sangre Fria",
    ingrediente: ["sangre"],
    humana: false,
    animal: false,
  },
  {
    bebida: 2,
    cliente: vampiro,
    precio: 10,
    nombre: "Sangre Fria",
    ingrediente: ["sangre"],
    humana: false,
    animal: false,
  },
  {
    bebida: 3,
    cliente: vampiro,
    precio: 11.5,
    nombre: "Organos Licuados",
    ingrediente: ["Higado, pulmon"],
    humana: false,
    animal: false,
  },
  {
    bebida: 4,
    cliente: vampiro,
    precio: 12,
    nombre: "Cuerdas Jugosas",
    ingrediente: ["Venas, Tendones, Ligamentos"],
    humana: false,
    animal: false,
  },
  
  //bebidas Angeles
  {
    bebida: 1,
    cliente: vampiro,
    precio: 10,
    nombre: "Sangre Fria",
    ingrediente: ["sangre"],
    humana: false,
    animal: false,
  },
  {
    bebida: 2,
    cliente: vampiro,
    precio: 10,
    nombre: "Sangre Fria",
    ingrediente: ["sangre"],
    humana: false,
    animal: false,
  },
  {
    bebida: 3,
    cliente: vampiro,
    precio: 11.5,
    nombre: "Organos Licuados",
    ingrediente: ["Higado, pulmon"],
    humana: false,
    animal: false,
  },
  {
    bebida: 4,
    cliente: vampiro,
    precio: 12,
    nombre: "Cuerdas Jugosas",
    ingrediente: ["Venas, Tendones, Ligamentos"],
    humana: false,
    animal: false,
  },

];
